### ISSUE TITLE
java.lang.reflect.UndeclaredThrowableException: null

### ISSUE THREAD

**Issue by MS666666** [dh-free/free-fs#2]
只要点击上传就报错，求大佬告知这是啥原因，只配置了七牛云
![image](https://github.com/dh-free/free-fs/assets/44149537/7a2afc7e-0503-437f-a952-0b2126171acd)
![image](https://github.com/dh-free/free-fs/assets/44149537/643923c9-d35d-4733-bdf9-d353ffc31523)

**Comment by dh-free** [comment]
麻烦附带配置文件信息

**Comment by MS666666** [comment]
@dh-free 
![image](https://github.com/dh-free/free-fs/assets/44149537/71352927-a75b-474b-b1ab-30f6f88565fa)

**Comment by dh-free** [comment]
请将type修改为qiuniu
files-server:

**Comment by MS666666** [comment]
刚改完

**Comment by MS666666** [comment]
请问一下刚才我改成本地模式时报了一个java.nio.file.NoSuchFileException 错误，我想请问一下如果我把类型改成本地的话，它这个临时文件路径如何修改？
![image](https://github.com/dh-free/free-fs/assets/44149537/75c35c3b-00a0-4308-aefc-5a0206ac2070)

**Comment by MS666666** [comment]
@dh-free

**Comment by dh-free** [comment]
local模式，如果是windows的话，建议指定绝对存储路径，比如：D://upload/，linux下：/data/upload/

**Comment by MS666666** [comment]
请问这是为啥一直转圈，但看七牛云上文件已经有了，控制台上也没有报错
![image](https://github.com/dh-free/free-fs/assets/44149537/c85d29ae-7b0f-486d-b1b0-816c7c08d905)
